from gdl.rendering.scene import Scene

demo = Scene(
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/DWF/ycg",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/PLAYERS/wiz/sum",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/LEVELS/levelE1",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/items/demo",
    #object_name="TRANS",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/PS2_WAD/POWERUPS",
    #object_name="BADMEAT",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/PLAYERS/VAL/BLU90",
    #object_name="VAL_BLU",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/PS2_WAD/PLAYERS/ARC/SFXBLU",
    #object_name="ARC_POWERB",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/PS2_WAD/PLAYERS/ARC/GRE90",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/PLAYERS/uni/gre",
    #object_name="uni_gre",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/monsters/lich",
    #object_name="lich",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/monsters/dragon",
    #object_name="dragon",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/monsters/drider",
    #object_name="drider",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/monsters/djinn",
    #object_name="djinn",
    objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/LEVELS/levelL1",
    #objects_dir="C:/Users/Moses/Desktop/gauntlet_modding/xbox_data/LEVELS/levelA1",
    #objects_dir="F:/My Files/Applications/Games/Xbox Stuff/GAMES/Gauntlet Dark Legacy/mods/diath/PLAYERS/VAL/jrd",
    )
demo.run()
